name: Сборка Python-агента
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  build-test:
    name: Build Immunity Python agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
      - name: Собираем библиотеку
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
      - name: Публикуем библиотеку
        env:
          TWINE_USERNAME: ${{ secrets.USR }}
          TWINE_PASSWORD: ${{ secrets.PWD }}
        run: |
          pip install --user --upgrade twine
          python3 -m twine upload dist/*
